# Generated by Django 5.2.7 on 2025-10-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_uid', models.CharField(max_length=64)),
                ('category_type', models.CharField(max_length=16)),
                ('category_uid', models.CharField(max_length=64)),
                ('space_uid', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['account_uid', 'category_type', 'category_uid'], name='spaces_cate_account_6b816e_idx')],
                'unique_together': {('account_uid', 'category_type', 'category_uid')},
            },
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('feed_item_uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('account_uid', models.CharField(max_length=64)),
                ('category_uid', models.CharField(max_length=64)),
                ('space_uid', models.CharField(max_length=64)),
                ('direction', models.CharField(blank=True, max_length=16, null=True)),
                ('amount_minor_units', models.BigIntegerField()),
                ('currency', models.CharField(max_length=8)),
                ('transaction_time', models.DateTimeField()),
                ('source', models.CharField(blank=True, max_length=64, null=True)),
                ('counterparty', models.CharField(blank=True, max_length=255, null=True)),
                ('spending_category', models.CharField(blank=True, max_length=64, null=True)),
                ('classified_category', models.CharField(blank=True, max_length=255, null=True)),
                ('classification_reason', models.CharField(blank=True, max_length=64, null=True)),
                ('raw_json', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['account_uid', 'space_uid', 'transaction_time'], name='spaces_feed_account_a8d0ee_idx'), models.Index(fields=['transaction_time'], name='spaces_feed_transac_4f4fe4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_uid', models.CharField(max_length=64)),
                ('category_uid', models.CharField(max_length=64)),
                ('last_transaction_time', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'unique_together': {('account_uid', 'category_uid')},
            },
        ),
    ]
