# Generated by Django 5.2.7 on 2025-10-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_classificationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationrule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationrule',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
