# Generated by Django 5.2.7 on 2026-03-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_classificationrule_daterange'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='feeditem',
            name='spender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
