# Generated by Django 5.2.7 on 2026-03-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_add_application_user_and_spender'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefinedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'user defined categories',
                'ordering': ('name',),
            },
        ),
    ]
