# Generated by Django 5.2.7 on 2026-03-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0006_add_user_defined_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="classificationrule",
            name="max_amount_minor_units",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="classificationrule",
            name="min_amount_minor_units",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
