# Generated by Django 5.2.7 on 2026-03-29 13:20

from django.db import migrations
from django.db.models import Max


COMBINED_CATEGORY = "Lifestyle & Entertainment"
COMBINED_REASON = "combined_category"
COMBINED_PATTERN = r"(?i)^(Lifestyle|Entertainment)$"


def seed_combined_category_and_rule(apps, schema_editor):
    UserDefinedCategory = apps.get_model("spaces", "UserDefinedCategory")
    ClassificationRule = apps.get_model("spaces", "ClassificationRule")
    FeedItem = apps.get_model("spaces", "FeedItem")

    UserDefinedCategory.objects.get_or_create(name=COMBINED_CATEGORY)

    rule = ClassificationRule.objects.filter(
        rule_type="classified_category_regex",
        category=COMBINED_CATEGORY,
        reason=COMBINED_REASON,
        pattern=COMBINED_PATTERN,
    ).first()
    if rule is None:
        max_position = ClassificationRule.objects.aggregate(Max("position"))["position__max"]
        ClassificationRule.objects.create(
            position=0 if max_position is None else max_position + 1,
            rule_type="classified_category_regex",
            category=COMBINED_CATEGORY,
            reason=COMBINED_REASON,
            pattern=COMBINED_PATTERN,
        )

    FeedItem.objects.filter(classified_category__in=["Lifestyle", "Entertainment"]).update(
        classified_category=COMBINED_CATEGORY,
        classification_reason=COMBINED_REASON,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0009_counterparty_and_transaction_notes"),
    ]

    operations = [
        migrations.RunPython(seed_combined_category_and_rule, migrations.RunPython.noop),
    ]
