# Generated by Django 5.2.7 on 2026-03-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0010_lifestyle_entertainment_category_rule"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingsSignalDismissal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("signal_type", models.CharField(max_length=32)),
                ("signal_key", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("signal_type", "signal_key"),
                "unique_together": {("signal_type", "signal_key")},
            },
        ),
    ]
